name: whiteboard
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  
  logger: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/MacPaw-Fixel/

  fonts:    
    - family: MacPaw
      fonts:
        - asset: assets/fonts/MacPaw-Fixel/FixelDisplay-Thin.otf
          weight: 100
        - asset: assets/fonts/MacPaw-Fixel/FixelDisplay-ThinItalic.otf
          style: italic
          weight: 100

        - asset: assets/fonts/MacPaw-Fixel/FixelDisplay-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/MacPaw-Fixel/FixelDisplay-ExtraLightItalic.otf
          style: italic
          weight: 200
        
        - asset: assets/fonts/MacPaw-Fixel/FixelDisplay-Light.otf
          weight: 300
        - asset: assets/fonts/MacPaw-Fixel/FixelDisplay-LightItalic.otf
          style: italic
          weight: 300
        
        - asset: assets/fonts/MacPaw-Fixel/FixelDisplay-Regular.otf
          weight: 400
        - asset: assets/fonts/MacPaw-Fixel/FixelDisplay-RegularItalic.otf
          style: italic
          weight: 400
        
        - asset: assets/fonts/MacPaw-Fixel/FixelDisplay-Medium.otf
          weight: 500
        - asset: assets/fonts/MacPaw-Fixel/FixelDisplay-MediumItalic.otf
          style: italic
          weight: 500
        
        - asset: assets/fonts/MacPaw-Fixel/FixelDisplay-SemiBold.otf
          weight: 600
        - asset: assets/fonts/MacPaw-Fixel/FixelDisplay-SemiBoldItalic.otf
          style: italic
          weight: 600
        
        - asset: assets/fonts/MacPaw-Fixel/FixelDisplay-Bold.otf
          weight: 700
        - asset: assets/fonts/MacPaw-Fixel/FixelDisplay-BoldItalic.otf
          style: italic
          weight: 700
        
        - asset: assets/fonts/MacPaw-Fixel/FixelDisplay-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/MacPaw-Fixel/FixelDisplay-ExtraBoldItalic.otf
          style: italic
          weight: 800
        
        - asset: assets/fonts/MacPaw-Fixel/FixelDisplay-Black.otf
          weight: 900
        - asset: assets/fonts/MacPaw-Fixel/FixelDisplay-BlackItalic.otf
          style: italic
          weight: 900
